### ISSUE TITLE
Problem in auto-creation

### ISSUE THREAD

**Issue by ProjetHost** [vbaranovskiy-plesk/whmcs-plugin#18]
When a client buy a reseller,
The resseller account is good created in plesk, but the command stay in waiting beacause i get this error :

Error code: 23000. Error message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' (SQL: insert into `mod_pleskaccounts` (`userid`, `usertype`, `panelexternalid`) values (1, reselleraccount, ae844b89-7d3a-4f84-bd70-1fda62769c6c))

**Comment by jas8522** [comment]
Sounds like you might have manually deleted the user with id 1 from the DB without deleting its matching mod_pleskaccounts entry. You should be able to just remove that entry from the DB under mod_pleskaccounts to fix this.

**Comment by jas8522** [comment]
I've now encountered this problem as well. The bug is that mod_pleskaccounts considers the userid the unique primary key. However it needs to be able to allow multiple entries under the same userid for when the Client has both a shared hosting and a reseller hosting account. You'll end up with two entries with the same userid, but different usertype and panelexternalid.

If you really think the table needs a primary key, then why not change it from the userid to the panelexternalid, as it (now) should be truly unique by using the associated Plesk ID (as compared to the old method in format whmcs_plesk_{$WHMCS_ID}).

I ran this to adjust the table structure to remove the primary key altogether:

`ALTER TABLE mod_pleskaccounts MODIFY userid INT NOT NULL;
ALTER TABLE mod_pleskaccounts DROP PRIMARY KEY;`

Then ran the query that had failed as a result of the primary key constraint. In the example above, that query would be:

`insert into mod_pleskaccounts (userid, usertype, panelexternalid) values (1, 'reselleraccount', 'ae844b89-7d3a-4f84-bd70-1fda62769c6c')`

Since the code explicitly checks for the usertype value on line 150 of plesk.php, this should work fine having multiple userid entries:

`->where('usertype', $params['type'])`

This solves the immediate problem, but... what happens when a client attempts to create multiple reseller accounts or multiple shared hosting accounts across different servers? It *looks* like it's just going to throw an exception and fail to create the account (lines 162-166 of plesk.php).

Perhaps instead the solution here is to *also* keep the serverid in the mod_pleskaccounts table and do slightly more precise lookups. That way each panelexternalid is associated with a matching pair of both userid and serverid.

createTableForAccountStorage is going to need some editing :)

**Comment by oneumyvakin** [comment]
Plesk internal ID EXTWHMCS-35

**Comment by jas8522** [comment]
Issue #25 may be the same thing.

**Comment by jas8522** [comment]
So now I get: 

`Error: Error code: 23000. Error message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5b252cbb-dd61-40d5-94f1-a6f3b948db38' for key 'panelexternalid' (SQL: insert into `mod_pleskaccounts` (`userid`, `usertype`, `panelexternalid`) values (2141, reselleraccount, 5b252cbb-dd61-40d5-94f1-a6f3b948db38))`

What I don't get is how that external ID could be identical... isn't it randomly generated? Or perhaps it's a hash based on a particular value, like the client's username? In other words: how is that panel external ID not unique @vbaranovskiy-plesk ?

**Comment by vbaranovskiy-plesk** [comment]
@jas8522 , External id is unique, we take it from WHMCS
https://github.com/plesk/whmcs-plugin/blob/master/lib/Plesk/Object/Customer.php#L22
As i can see, we are chek the table plesk_modaccounts and get a panelExternalId or empty string. Next we take an uuid property of WHMCS account (seems like it should be unique) if panelExternalId is empty to this moment.  Seesm like everything should works fine. 

Also, this property is specified in one place and it never changes after (i'm talking about possible scenario when we checked table plesk_modaccounts, didn't find anything and specify this property somewhere else)
https://github.com/plesk/whmcs-plugin/blob/master/lib/Plesk/Object/Customer.php#L17

PS. I have watched your pull requests. Everything fine with them, but i didn't close because of our politic when it should be verified by our test engineers before.

**Comment by jas8522** [comment]
Ohh. I see, I thought the panelexternalid was from Plesk. In this instance if that's tied to the client, then that field also can't be unique because it'll always be the same per client. Oh well I suppose it doesn't need to be.

Thanks, re the pull requests :)

**Comment by alexanderrieder** [comment]
So is this fixed?

**Comment by vbaranovskiy-plesk** [comment]
@alexanderrieder yes, but for new instances of whmcs only.
https://github.com/plesk/whmcs-plugin/commit/fa223d1a182d6ccec840ee91d7cb8af1d1596541

Unfortnally, to fix the existing installation you need to drop and add indexes to this table manually.

**Comment by vbaranovskiy-plesk** [comment]
Manual fix of the issue:
ALTER TABLE mod_pleskaccounts DROP PRIMARY KEY, ADD PRIMARY KEY(panelexternalid, usertype);

**Comment by offgridengineering** [comment]
Plesk have another solution:

ALTER TABLE mod_pleskaccounts MODIFY userid INT NOT NULL;
ALTER TABLE mod_pleskaccounts DROP PRIMARY KEY; 
ALTER TABLE mod_pleskaccounts DROP INDEX panelexternalid; 
ALTER TABLE mod_pleskaccounts ADD PRIMARY KEY(panelexternalid, usertype);
