### ISSUE TITLE
Add feature "WHMCS customer has always only one subscription"

### ISSUE THREAD

**Issue by vbaranovskiy-plesk** [vbaranovskiy-plesk/whmcs-plugin#2]
Many providers who tries Plesk+WHMCS asks the same question: 
- I think the most ideal setup for WHMCS + Plesk is : 1 hosting account on WHMCS translated to 1 subcription and 1 customer on Plesk so that we can work the same way with cPanel for this login issue.
- I want one customer only have one subscription. Can you give me a solution for that ?

**Comment by vbaranovskiy-plesk** [comment]
Feature is added by this commit

https://github.com/plesk/whmcs-plugin/commit/26b4a829f05795b23d481237f65e0c371f2797b7

**Comment by vbaranovskiy-plesk** [comment]
Fixed bugs:
https://github.com/plesk/whmcs-plugin/commit/f389717ac0f383b4516eab951affd2a3102ba924
https://github.com/plesk/whmcs-plugin/commit/1d09e08d7a6dd0f99098cc4e470e8258dc120862
https://github.com/plesk/whmcs-plugin/commit/408fb78e9701fe7fd5e997400ea4681f28fe13a0

**Comment by cenourinha** [comment]
Hi @vbaranovskiy-plesk , can you clarify how this work? I see this translation in the commit:

"You have reached the limit of allowed subscriptions per one account (@ACCOUNT_LIMIT@ subscription(s) allowed). To order a new subscription you should use another account."

Does this mean that a WHMCS Client can only have a Plesk Hosting Account and will need to have a different WHMCS Client Account in order to have a new Plesk Hosting Account?

What will really happen if i uncomment "account_limit = 1" on the config.ini file?

**Comment by vbaranovskiy-plesk** [comment]
@cenourinha sorry for delay. Somehow, i've missed your question.
Yes, you've understood the main point correctly. 
Customer will see an error when he tries to buy a second (> 1) plesk's subscription (Plesk Hosting Account). This limit became the one additional validation rule.

**Comment by cenourinha** [comment]
What if we want the customer to have multiple accounts? For example, a web agency subscribing multiple hosting accounts for their customers website, but want to give them access to Plesk individually (without using the Reseller option)?
