### ISSUE TITLE
Subscriptions in one Account

### ISSUE THREAD

**Issue by fuyonet** [vbaranovskiy-plesk/whmcs-plugin#44]
WHMCS support sent me here. They also hope that my problem will be solved. 

Quote:
The Plesk module for WHMCS is developed and maintained by Plesk themselves: https://github.com/plesk/whmcs-plugin So I'm sure their team will be pleased to receive your feedback on their module, and hopefully can consider changing their design in future.

more than 90% of my customers order more than one web package from me. earlier (plesk12.5) every time a new customer was created in Plesk and a subscription.

The customers want it the same way. 

Now WHMCS creates only one customer and throws all additional subscriptions into the first customer account. Usernames and passwords which we show as login in our customer center don't work anymore. only the first one. 

can you please change that or at least leave a config ?
[X] allow multiple accounts

**Comment by mgilank** [comment]
we need this to fix in onyx 17 please

**Comment by vbaranovskiy-plesk** [comment]
The issue is not depending of Plesk version
The public bug id is EXTWHMCS-3
The fix will be following: 
- the config option "allow multiple accounts" will be added (default value: false). 
Some clients doesn't need a login with credentials of certain user - they just need to log in to the list of subscriptions
