### ISSUE TITLE
Fatal error 1014 at every product creation

### ISSUE THREAD

**Issue by noahchrde** [vbaranovskiy-plesk/whmcs-plugin#48]
`Order Accept Encountered Problems
Error code: 1014. Error message: Parser error: Request is invalid. Error in line 6: Element 'owner-id': '' is not a valid value of the atomic type 'int'.`

Error at every product creation.

**Comment by vbaranovskiy-plesk** [comment]
@Noahkemm,

What do you mean "Every product creation"? Is it about a WHMCS product's creation or buying some subscription by some customer?

Please, enable Module log (Whmcs admin UI -> Utilities -> Module log) and reproduce the issue. Log will have entry with fallen API-RPC request to Plesk. It could help a reason, why such thing is happened

**Comment by oussamadouhou** [comment]
I have the same issue here. It seems like that WHMCS is unable to parse the owner id to plesk what causing this error.

I took a look into the module log and find out that, indeed, the ownerid field is empty. This is what i got:
`<?xml version="1.0" encoding="UTF-8"?><packet version="1.6.3.2">
<webspace>
    <add>
        <gen_setup>
            <name>domain.name</name>
            <owner-id></owner-id>
            <htype>vrt_hst</htype>
            <status>0</status>
        </gen_setup>
        <hosting>
            <vrt_hst>
                <property>
                    <name>ftp_login</name>
                    <value>loginname</value>
                </property>
                <property>
                    <name>ftp_password</name>
                    <value>generatedpassword</value>
                </property>
                                    `

I think we need to look where the ownerid is comming from.

> `Order Accept Encountered Problems Error code: 1014. Error message: Parser error: Request is invalid. Error in line 6: Element 'owner-id': '' is not a valid value of the atomic type 'int'.`
> 
> Error at every product creation.

### Solution
This is caused by the Plesk product being set to **"Other"** rather than **"Shared Hosting"**.

Changing the product type under **"Setup"** > **"Products / Services"** > **"Products / Services"** and change your service from other to **"Shared hosting"** instead of **"Other"** resolves this error.
